import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/db';

const mockBusinesses = [
  {
    userId: 'b1',
    name: 'Studio 22 Barbershop',
    contactPerson: 'Atanas',
    phone: '+359 88 123 4567',
    email: 'studio22@plovdiv.bg',
    address: 'bulevard "Vasil Aprilov" 48, Plovdiv 4002',
    description: 'Creative barbershop at Medical University. Modern cuts & beard styling.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1607780082253-e40c2e7c2c00?w=400',
    status: 'approved',
    rating: 5.0,
    reviewCount: 218,
  },
  {
    userId: 'b2',
    name: 'Barber Studio',
    contactPerson: 'Petar',
    phone: '+359 88 234 5678',
    email: 'barberstudio@plovdiv.bg',
    address: 'ulitsa "Lyuben Karavelov" 59, Plovdiv 4002',
    description: 'Professional barbers near Ancient Theatre. Best fades in city.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400',
    status: 'approved',
    rating: 4.9,
    reviewCount: 156,
  },
  {
    userId: 'b3',
    name: 'Studio 38 Barber Shop',
    contactPerson: 'Georgi',
    phone: '+359 88 345 6789',
    email: 'studio38@plovdiv.bg',
    address: 'bulevard "Maritsa" 27, Plovdiv 4003',
    description: 'Premium beard services & hot towel shaves in Karshiaka.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1503951911965-4d7a8f87bc6b?w=400',
    status: 'approved',
    rating: 4.8,
    reviewCount: 89,
  },
  {
    userId: 'b4',
    name: 'Barber Studio 2',
    contactPerson: 'Maria',
    phone: '+359 88 456 7890',
    email: 'barberstudio2@plovdiv.bg',
    address: 'ulitsa "Filip Makedonski" 49B, Plovdiv 4000',
    description: 'Second location near Plovdiv Central. Quality service.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5f7ff8747e29?w=400',
    status: 'approved',
    rating: 5.0,
    reviewCount: 203,
  },
  {
    userId: 'b5',
    name: 'Karagyozov Barbershop',
    contactPerson: 'Karagyozov',
    phone: '+359 88 567 8901',
    email: 'karagyozov@plovdiv.bg',
    address: 'bulevard "Iztochen" 51, Plovdiv 4000',
    description: 'Traditional techniques with modern flair. Classic cuts.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b09?w=400',
    status: 'approved',
    rating: 4.7,
    reviewCount: 178,
  },
  {
    userId: 'b6',
    name: 'BarberShop Basri',
    contactPerson: 'Basri',
    phone: '+359 88 678 9012',
    email: 'basri@plovdiv.bg',
    address: 'ulitsa "Shipka" 27, Plovdiv 4003',
    description: 'Professional barber with coloring & styling services.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1603398938378-e54e5c91eeb3?w=400',
    status: 'approved',
    rating: 4.9,
    reviewCount: 124,
  },
  {
    userId: 'b7',
    name: 'Fit Barber Studio',
    contactPerson: 'Fit Team',
    phone: '+359 88 789 0123',
    email: 'fitbarber@plovdiv.bg',
    address: 'ulitsa "Macedonia" 47-49, Plovdiv 4013',
    description: 'Modern barbershop in Hristo Botev area.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=400',
    status: 'approved',
    rating: 4.6,
    reviewCount: 67,
  },
  {
    userId: 'b8',
    name: 'Meshari Barbers',
    contactPerson: 'Meshari',
    phone: '+359 88 890 1234',
    email: 'meshari@plovdiv.bg',
    address: 'bulevard "Hristo Botev" 138B, Plovdiv 4000',
    description: 'Expert in fades, beard sculpting & modern styling.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1599351615870-7f2e63f57096?w=400',
    status: 'approved',
    rating: 4.8,
    reviewCount: 145,
  },
  {
    userId: 'b9',
    name: 'Oxygen Barbershop',
    contactPerson: 'Stanimir',
    phone: '+359 88 901 2345',
    email: 'oxygen@plovdiv.bg',
    address: 'Plovdiv Center',
    description: 'Fresh approach to classic barbering. Premium products.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1519558021667-99fdd6f660f6?w=400',
    status: 'approved',
    rating: 5.0,
    reviewCount: 92,
  },
  {
    userId: 'b10',
    name: 'Barber Shop MEMO',
    contactPerson: 'Memo',
    phone: '+359 88 012 3456',
    email: 'memo@plovdiv.bg',
    address: 'Plovdiv',
    description: 'Top-rated barbershop. Excellent service & friendly staff.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1633681926046-69b0646f70a7?w=400',
    status: 'approved',
    rating: 4.6,
    reviewCount: 234,
  },
  {
    userId: 'b11',
    name: 'Moustache Barber Shop',
    contactPerson: 'Mustache Team',
    phone: '+359 88 123 4568',
    email: 'moustache@plovdiv.bg',
    address: 'Plovdiv',
    description: 'Moustache specialists! Full beard & hair services.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1624880614138-f65b8d3cf84d?w=400',
    status: 'approved',
    rating: 4.7,
    reviewCount: 88,
  },
  {
    userId: 'b12',
    name: 'Evolution Barber Shop',
    contactPerson: 'Evolution Team',
    phone: '+359 88 234 5679',
    email: 'evolution@plovdiv.bg',
    address: 'ulitsa "Rayko" 85, Plovdiv',
    description: 'Modern techniques, traditional values.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1588195538326-c5b1acd1f7b0?w=400',
    status: 'approved',
    rating: 5.0,
    reviewCount: 156,
  },
  {
    userId: 'n1',
    name: 'Luxe Nails Plovdiv',
    contactPerson: 'Elena',
    phone: '+359 88 111 2233',
    email: 'luxenails@plovdiv.bg',
    address: 'bulevard "Russia" 6, Plovdiv 4002',
    description: 'Premium nail studio. Gel, acrylic & nail art. Near Tsar Simeon Garden.',
    category: 'nails',
    imageUrl: 'https://images.unsplash.com/photo-1604654894610-df2494f9c7f8?w=400',
    status: 'approved',
    rating: 4.9,
    reviewCount: 156,
  },
  {
    userId: 'n2',
    name: 'Nail Art Studio',
    contactPerson: 'Victoria',
    phone: '+359 88 222 3344',
    email: 'nailart@plovdiv.bg',
    address: 'ulitsa "Kamenitsa" 15, Plovdiv 4000',
    description: 'Creative nail art & luxury manicures in city center.',
    category: 'nails',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37a?w=400',
    status: 'approved',
    rating: 4.8,
    reviewCount: 89,
  },
  {
    userId: 'n3',
    name: 'Glamour Nails',
    contactPerson: 'Anna',
    phone: '+359 88 333 4455',
    email: 'glamournails@plovdiv.bg',
    address: 'ulitsa "Dragan Minkov" 12, Plovdiv 4003',
    description: 'Professional nail care & spa treatments.',
    category: 'nails',
    imageUrl: 'https://images.unsplash.com/photo-1516975080664-ed2fc2a6d278?w=400',
    status: 'approved',
    rating: 4.7,
    reviewCount: 67,
  },
  {
    userId: 'n4',
    name: 'Perfect Nails Spa',
    contactPerson: 'Mirabella',
    phone: '+359 88 444 5566',
    email: 'perfectnails@plovdiv.bg',
    address: 'bulevard "Dunav" 35, Plovdiv 4003',
    description: 'Luxury nail spa & pedicure in Severen area.',
    category: 'nails',
    imageUrl: 'https://images.unsplash.com/photo-1632345031635-6e3d8f84c43d?w=400',
    status: 'approved',
    rating: 4.9,
    reviewCount: 203,
  },
  {
    userId: 'h1',
    name: 'Hair Fashion Plovdiv',
    contactPerson: 'Style Team',
    phone: '+359 88 555 6677',
    email: 'hairfashion@plovdiv.bg',
    address: 'ulitsa "Gladston" 42, Plovdiv 4000',
    description: 'Modern hair styling & professional coloring.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1607780082253-e40c2e7c2c00?w=400',
    status: 'approved',
    rating: 4.8,
    reviewCount: 145,
  },
  {
    userId: 'h2',
    name: 'Princess Hair Studio',
    contactPerson: 'Princess',
    phone: '+359 88 666 7788',
    email: 'princess@plovdiv.bg',
    address: 'ulitsa "Otets Paisiy" 28, Plovdiv 4002',
    description: 'Luxury hair & beauty services for women.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400',
    status: 'approved',
    rating: 4.9,
    reviewCount: 178,
  },
  {
    userId: 'h3',
    name: 'Gentlemens Club Plovdiv',
    contactPerson: 'Club Team',
    phone: '+359 88 777 8899',
    email: 'gentlemen@plovdiv.bg',
    address: 'bulevard "Shesti April" 66, Plovdiv 4000',
    description: 'Premium grooming for gentlemen only.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5f7ff8747e29?w=400',
    status: 'approved',
    rating: 4.8,
    reviewCount: 234,
  },
  {
    userId: 'h4',
    name: 'New Look Hairdressing',
    contactPerson: 'New Look',
    phone: '+359 88 888 9900',
    email: 'newlook@plovdiv.bg',
    address: 'ulitsa "Simeon Veliki" 18, Plovdiv 4001',
    description: 'Classic hairdressing & styling for all ages.',
    category: 'hair',
    imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b09?w=400',
    status: 'approved',
    rating: 4.6,
    reviewCount: 123,
  },
];

export async function GET() {
  try {
    // Check if businesses already exist
    const existing = await prisma.business.findMany();
    
    if (existing.length > 0) {
      return NextResponse.json({ 
        message: 'Businesses already exist', 
        count: existing.length 
      });
    }

    // Create all businesses
    const businesses = await Promise.all(
      mockBusinesses.map(b => prisma.business.create({ data: b }))
    );

    return NextResponse.json({ 
      message: 'Seeded businesses', 
      count: businesses.length 
    });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json({ error: 'Failed to seed' }, { status: 500 });
  }
}

export async function POST() {
  // Alias POST to GET for seeding
  return GET();
}